name: "ðŸ”¥ Add Banned Word"
description: Add Banned Word
title: "Banned prompt: "
labels: ["banned prompt"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your issue report (à¹‘>Ø‚<à¹‘ï¼‰
  - type: input
    id: prompt
    attributes:
      label: Banned Word
      description: Enter the Midjourney banned word you need to addï½ž
      placeholder: |
        Prompt
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: A little self-check
      description: Before you submit the issue, please confirm whether you have completed the following checks:
      options:
        - label: If it is a network problem, I have checked whether the network connection and settings are normal and have been fully tested
          required: true
        - label: This prompt does not exist in [banned_words](https://github.com/PyramidDevelopers/midjourney-api/blob/main/banned_words.txt)
          required: true
