name: "🐛 New Issue"
description: Report a new issue
title: "🐛 "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you very much for your issue report (๑>؂<๑), in order for us to locate the source of the problem more quickly, please fill out this Issue form as completely as possible.
  - type: textarea
    id: description
    attributes:
      label: Issue Summary
      description: Describe the issue you are experiencing in detail (if there are any errors, please paste them here)～
      placeholder: |
        If convenient, please provide more detailed log information.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Method
      description: |
        Please provide your method of reproducing this issue here.
        To save time in communication, please test multiple times before submitting the issue to ensure that it can be repeatedly reproduced (not a network issue).
      placeholder: "Be careful to hide all private information in the pasted commands (*/ω＼*)"
    validations:
      required: true
  - type: textarea
    id: environment-info
    attributes:
      label: Environment Information
      description: Please provide the following information as detailed as possible～
      placeholder: Your environment information～
      value: |
        -  OS: Type and version of operating system
        -  Python: Python version (`python --version`)
        -  Others: Other information
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Please provide any reasons you think may have caused this issue
      placeholder: If there is additional information, please fill it in here～
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: A Little Self-Check
      description: Before you submit the issue, please confirm that you have completed the following checks:
      options:
        - label: Thoroughly read [README.md](https://github.com/PyramidDevelopers/midjourney-api), especially the parts related to this issue
          required: true
        - label: If it is a network problem, the network connection and settings have been checked to be normal, and after sufficient testing, it is believed to be a problem with the project itself
          required: true
        - label: This issue is not a duplicate in [issues](https://github.com/PyramidDevelopers/midjourney-api/ssues)
          required: true
