name: Build, Test and Deploy to Production ECR
on:
  push:
    branches:
      - master
    paths-ignore:
    - 'README.md'
    - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    # use a known build environment
    container: python:3.9-slim

    # Required services    
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install libraries for PostgreSQL
        run: |
          apt-get update
          apt-get install -y gcc libpq-dev build-essential cmake tesseract-ocr libtesseract-dev libcurl4-openssl-dev libssl-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1 

      - name: Get Secrets from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
            secret-ids:  |
                arn:aws:secretsmanager:us-east-1:180299548740:secret:prod/AthenaAI/secrets-aq0wp3
            parse-json-secrets: true



      # - name: Run unit tests with nose
      #   run: |
      #     export FLASK_APP=service:app
      #     nosetests
      #   env:
      #     DATABASE_URI: "postgresql://postgres:pgs3cr3t@postgres:5432/testdb"
  

  
  deploy: 
    name: Deploy to ECR
    runs-on: ubuntu-latest
    needs: build
    env:
        PRODUCTION: true
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push server to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: athena
        IMAGE_TAG: backend-prod
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f server/Dockerfile server
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Build, tag, and push bot to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: athena
        IMAGE_TAG: bot-prod
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f bot/Dockerfile bot
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

